# Generated by Django 6.0.6 on 2026-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalityentry',
            name='description',
        ),
        migrations.AddField(
            model_name='hospitalityentry',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('not_issued', 'Not Issued')], default='not_issued', max_length=15),
        ),
    ]
