# Generated by Django 6.0.6 on 2026-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0002_remove_hospitalityentry_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='description',
        ),
        migrations.AddField(
            model_name='hospitalityentry',
            name='amount',
            field=models.PositiveIntegerField(default=1, help_text='Number of items per person in entry'),
        ),
        migrations.AddField(
            model_name='types',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
