# Generated by Django 6.0.6 on 2026-06-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0003_remove_types_description_hospitalityentry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('coins', 'Coins'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
