# Generated by Django 6.0.6 on 2026-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0004_types_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.CharField(choices=[('card', 'Card'), ('coin', 'Coin'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='types',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Only for card type: the value of the card. For coin type, the value is always 1. For none type, the value is 0.', max_digits=10),
        ),
    ]
