# Generated by Django 6.0.6 on 2026-06-24 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditatie', '0007_remove_accessentry_type_accessentry_access_type_and_more'),
        ('hospitality', '0005_alter_types_type_alter_types_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditatie.event')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditatie.accessentry')),
                ('space', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitality.space')),
            ],
            options={
                'verbose_name_plural': 'Space Entries',
            },
        ),
    ]
