# Generated by Django 6.0.6 on 2026-06-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditatie', '0007_remove_accessentry_type_accessentry_access_type_and_more'),
        ('hospitality', '0006_space_spaceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.TextField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditatie.accessentry')),
            ],
            options={
                'verbose_name_plural': 'Rider Entries',
            },
        ),
    ]
