# Generated by Django 6.0.6 on 2026-06-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditatie', '0002_event_alter_entry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditatie.event'),
        ),
    ]
