# Generated by Django 6.0.6 on 2026-06-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditatie', '0003_entry_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditatie.event')),
            ],
            options={
                'verbose_name_plural': 'Entrances',
            },
        ),
        migrations.CreateModel(
            name='AccessEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_tickets', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditatie.event')),
                ('entrance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditatie.entrance')),
            ],
            options={
                'verbose_name': 'Access Entry',
                'verbose_name_plural': 'Access Entries',
            },
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
