# Generated by Django 6.0.6 on 2026-06-24 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditatie', '0004_entrance_accessentry_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditatie.event')),
            ],
            options={
                'verbose_name_plural': 'Access Levels',
            },
        ),
        migrations.AddField(
            model_name='accessentry',
            name='access_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accreditatie.accesslevel'),
        ),
    ]
