# Generated by Django 6.0.6 on 2026-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditatie', '0005_accesslevel_accessentry_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessentry',
            name='type',
            field=models.CharField(choices=[('crew', 'Crew'), ('artist', 'Artist'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
