# Generated by Django 6.0.6 on 2026-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accreditatie', '0006_accessentry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessentry',
            name='type',
        ),
        migrations.AddField(
            model_name='accessentry',
            name='access_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('crew', 'Crew'), ('guest', 'Guest')], default='crew', max_length=10),
        ),
        migrations.AddField(
            model_name='accessentry',
            name='status',
            field=models.CharField(choices=[('arrived', 'Arrived'), ('not_arrived', 'Not Arrived'), ('cancelled', 'Cancelled')], default='not_arrived', max_length=15),
        ),
    ]
